export const fps = 30;

export const video = {
  title: "Daily Notes That Protect Care",
  subtitle: "Professional documentation training for home health staff",
  brand: "Quality One Care Home Health Inc.",
  tagline: "We Care with Golden Hands.",
  audience: "Caregiver and field staff training",
  durationInFrames: 7200,
};

export const scenes = [
  {
    id: "opening",
    start: 0,
    duration: 540,
    eyebrow: "Quality One Care Training",
    title: "Daily notes protect the client, the caregiver, and the agency",
    body: "This module explains how to write complete, accurate, professional daily notes after every visit.",
    metric: "4 min",
    metricLabel: "staff training module",
  },
  {
    id: "risk",
    start: 540,
    duration: 660,
    eyebrow: "Chapter 01",
    title: "Documentation supports trust and compassion",
    body: "Quality One Care delivers home health services built on coordinated teamwork, compassion, dignity, and patient-centered care.",
    metric: "Record",
    metricLabel: "what happened today",
  },
  {
    id: "workflow",
    start: 1200,
    duration: 720,
    eyebrow: "Chapter 02",
    title: "Use one standard note structure",
    body: "Whether the service is skilled nursing, therapy, adult care, pediatric care, home infusion, or hospice, the note must clearly tell the care story.",
    metric: "5 parts",
    metricLabel: "one complete note",
  },
  {
    id: "quality",
    start: 1920,
    duration: 720,
    eyebrow: "Chapter 03",
    title: "Write observable details",
    body: "Use facts someone can understand later: wound care, medication management, vital signs, mobility, hygiene, companionship, safety, and client response.",
    metric: "Facts",
    metricLabel: "not opinions",
  },
  {
    id: "escalation",
    start: 2640,
    duration: 660,
    eyebrow: "Chapter 04",
    title: "Flag changes early",
    body: "Report important changes in condition, behavior, safety, appetite, medication routine, family concerns, or therapy tolerance according to agency process.",
    metric: "Alert",
    metricLabel: "when something changes",
  },
  {
    id: "privacy",
    start: 3300,
    duration: 660,
    eyebrow: "Chapter 05",
    title: "Protect client information every time",
    body: "Only document what belongs in the care record. Do not share private client details through personal texts or unsecured channels.",
    metric: "PHI",
    metricLabel: "handle with care",
  },
  {
    id: "example",
    start: 3960,
    duration: 780,
    eyebrow: "Chapter 06",
    title: "Turn a weak note into a strong note",
    body: "A professional note is brief, factual, and useful. It explains the visit without adding personal judgment or unnecessary detail.",
    metric: "Better",
    metricLabel: "clear and useful",
  },
  {
    id: "checklist",
    start: 4740,
    duration: 780,
    eyebrow: "Chapter 07",
    title: "Use the final note checklist",
    body: "Before submitting, check time accuracy, care tasks, client response, changes or concerns, and privacy.",
    metric: "Review",
    metricLabel: "before submit",
  },
  {
    id: "close",
    start: 5520,
    duration: 960,
    eyebrow: "Final reminder",
    title: "If a supervisor reads it tomorrow, will the visit be clear?",
    body: "That is the standard. Clear notes support safer care, stronger teamwork, independence, dignity, and better follow-up.",
    metric: "QOC",
    metricLabel: "professional standard",
  },
  {
    id: "outro",
    start: 6480,
    duration: 720,
    eyebrow: "Quality One Care",
    title: "Thank you for caring with golden hands",
    body: "Complete your daily notes on time, keep them factual, and protect every client record.",
    metric: "Done",
    metricLabel: "training complete",
  },
];

export const checklist = [
  "Visit time is accurate",
  "Care tasks are specific",
  "Client response is included",
  "Changes or concerns are flagged",
  "Private information is protected",
];

export const speakerScript = [
  "Welcome to Quality One Care Home Health. This training explains how daily notes protect our clients and support professional care.",
  "Quality One Care is built around trust, compassion, teamwork, and helping patients experience comfort, independence, dignity, and normalcy at home.",
  "Use one standard structure across service lines: skilled nursing, therapy, adult care, pediatric care, home infusion, and hospice.",
  "Write observable facts. Include care delivered, client response, changes observed, and details that help the next care team member act wisely.",
  "When something changes, document it clearly and follow the agency process for reporting concerns.",
  "Client information must be protected. Use approved systems and keep private details inside the care record.",
  "A weak note says the client was fine. A strong note explains what care was provided and what was observed.",
  "Before you submit, use the final checklist. Time, care, response, changes, privacy.",
  "If a supervisor reads your note tomorrow, the visit should be clear without needing to call you.",
  "Thank you for your professionalism and for caring with golden hands.",
];
